### ISSUE TITLE
Package Install Issue Due to `staplr` Dependency

### ISSUE THREAD

**Issue by njlyon0** [oganm/wizaRd#2]
Hi! I love `wizaRd` but ran into an error when trying to install it on a new machine. 

Here's my error:
```
devtools::install_github('oganm/wizaRd')

> ERROR: dependency ‘staplr’ is not available for package ‘wizaRd’
> * removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/wizaRd’
> Warning message:
> In i.p(...) :
>  installation of package ‘/var/folders/9m/7tv5z0_j2q34mnkv7907vm540000gn/T//Rtmpkl3V4P/file8f995ab077ff/wizaRd_1.0.0.9000.tar.gz’ had non-zero exit status
```

I believe this is due to `staplr` getting removed from CRAN recently (see [here](https://cran.r-project.org/web/packages/staplr/index.html)). That missing dependency then causes `wizaRd`'s installation to fail.

If you've encountered this before and know the solve please let me know!

**Comment by oganm** [comment]
Thanks for letting me know. Pushed a fix to install staplr from Github for
now.

Cheers,
Ogan

**Comment by njlyon0** [comment]
I'm still getting an install error, I think because `staplr` is still listed in the "Imports" bit of `DESCRIPTION` ([line 12](https://github.com/oganm/wizaRd/blob/master/DESCRIPTION#L12))

**Comment by oganm** [comment]
It being listed on imports should be fine. It is still an imported dependency just like diceSyntax. I was just able to install after deleting my local copy of staplr. Could you try doing `devtools::install_github("pridiltal/staplr")` and see if it installs on its own?

**Comment by njlyon0** [comment]
That worked! I actually think I was getting an error on the `staplr`development version install because I didn't have Java installed (new computer problems). That error then prevented your package from installing.

Installation was successful now though and thanks for your help!

**Comment by oganm** [comment]
no worries. have fun
